# Generated by Django 6.0 on 2026-01-09 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_enabled', models.BooleanField(default=True)),
                ('max_cache_size_mb', models.PositiveIntegerField(default=10240, help_text='Max cache size in MB (default 10GB)')),
                ('auto_cleanup_enabled', models.BooleanField(default=True)),
                ('cleanup_after_days', models.PositiveIntegerField(default=30, help_text='Delete cached files older than N days')),
                ('max_concurrent_downloads', models.PositiveIntegerField(default=2)),
                ('min_delay_between_downloads', models.PositiveIntegerField(default=5, help_text='Minimum seconds between downloads (rate limit protection)')),
                ('preferred_format', models.CharField(default='m4a', max_length=20)),
                ('preferred_bitrate', models.PositiveIntegerField(default=128, help_text='Preferred bitrate in kbps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache Settings',
                'verbose_name_plural': 'Cache Settings',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000)),
                ('playlist_type', models.CharField(choices=[('user', 'User Playlist'), ('curated', 'Curated'), ('lofi', 'LoFi Mix'), ('cyberpunk', 'Cyberpunk Mix')], default='user', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds', null=True)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('local', 'Local File')], default='youtube', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='YouTube Video-ID', max_length=100)),
                ('source_url', models.URLField(blank=True, help_text='For local files', max_length=2000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('is_cached', models.BooleanField(default=False)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('cache_file_path', models.CharField(blank=True, help_text='Path to cached file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='music_playe_source__f8492a_idx'), models.Index(fields=['is_cached'], name='music_playe_is_cach_c25387_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaylistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='music_player.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='music_player.track')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'position')},
            },
        ),
        migrations.CreateModel(
            name='AudioCacheLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('completed', 'Completed'), ('failed', 'Failed'), ('cached', 'Already Cached'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('download_duration_seconds', models.FloatField(blank=True, null=True)),
                ('bandwidth_bytes_per_sec', models.FloatField(blank=True, null=True)),
                ('download_started_at', models.DateTimeField(blank=True, null=True)),
                ('download_completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_started_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('yt_dlp_version', models.CharField(blank=True, max_length=50)),
                ('audio_format', models.CharField(blank=True, default='m4a', max_length=20)),
                ('audio_bitrate', models.PositiveIntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cache_logs', to='music_player.track')),
            ],
            options={
                'verbose_name': 'Audio Cache Log',
                'verbose_name_plural': 'Audio Cache Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='music_playe_status_a654a1_idx'), models.Index(fields=['started_at', 'completed_at'], name='music_playe_started_be04f8_idx'), models.Index(fields=['video_id', 'status'], name='music_playe_video_i_8b58d8_idx')],
            },
        ),
    ]
