# Generated by Django 6.0 on 2026-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('user', 'User Playlist'), ('curated', 'Curated')], default='user', max_length=20),
        ),
    ]
