# Generated by Django 6.0 on 2026-01-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_alter_playlist_playlist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='system_key',
            field=models.CharField(blank=True, help_text="Unique key for system playlists (e.g., 'video_help', 'news')", max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('user', 'User Playlist'), ('curated', 'Curated'), ('system', 'System Playlist')], default='user', max_length=20),
        ),
    ]
