# Generated by Django 6.0 on 2026-01-10 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chutney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitevent',
            name='build_time_ms',
            field=models.IntegerField(blank=True, help_text='Circuit build time in ms (for BUILT events)', null=True),
        ),
        migrations.AlterField(
            model_name='circuitevent',
            name='event_time',
            field=models.DateTimeField(help_text='Event timestamp'),
        ),
        migrations.AlterField(
            model_name='circuitevent',
            name='path',
            field=models.JSONField(default=list, help_text='Circuit path (list of hops)'),
        ),
        migrations.AlterField(
            model_name='circuitevent',
            name='path_length',
            field=models.IntegerField(default=0, help_text='Number of hops'),
        ),
        migrations.AlterField(
            model_name='circuitevent',
            name='raw_event',
            field=models.TextField(blank=True, help_text='Raw event data from Stem'),
        ),
        migrations.AlterField(
            model_name='circuitevent',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for FAILED/CLOSED', max_length=100),
        ),
        migrations.AlterField(
            model_name='circuitevent',
            name='remote_reason',
            field=models.CharField(blank=True, help_text='Remote-side reason', max_length=100),
        ),
        migrations.AlterField(
            model_name='circuitevent',
            name='source_node',
            field=models.ForeignKey(blank=True, help_text='Node that reported the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_events', to='chutney.tornode'),
        ),
        migrations.AlterField(
            model_name='circuitevent',
            name='status',
            field=models.CharField(blank=True, help_text='Circuit status string', max_length=50),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='assume_reachable',
            field=models.BooleanField(default=True, help_text='AssumeReachable 1 - Skips reachability tests'),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='base_control_port',
            field=models.IntegerField(default=8000, help_text='Base port for Tor Control Ports (8000, 8001, ...)', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='base_dir_port',
            field=models.IntegerField(default=7000, help_text='Base port for Directory Ports (7000, 7001, ...)', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='base_or_port',
            field=models.IntegerField(default=5000, help_text='Base port for Onion Router Ports (5000, 5001, ...)', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='base_socks_port',
            field=models.IntegerField(default=9000, help_text='Base port for SOCKS proxies (9000, 9001, ...)', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='bootstrap_progress',
            field=models.IntegerField(default=0, help_text='Bootstrap progress in percent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='capture_enabled',
            field=models.BooleanField(default=True, help_text='Enable traffic capture on all nodes'),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='capture_filter',
            field=models.CharField(blank=True, default='tcp port 5000-5100 or tcp port 9000-9100', help_text='tcpdump filter expression', max_length=200),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='capture_rotate_interval',
            field=models.IntegerField(default=3600, help_text='Capture rotation interval in seconds', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='consensus_fresh_until',
            field=models.DateTimeField(blank=True, help_text='Consensus fresh until', null=True),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='consensus_valid',
            field=models.BooleanField(default=False, help_text='Valid consensus available'),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='consensus_valid_after',
            field=models.DateTimeField(blank=True, help_text='Consensus valid after', null=True),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='consensus_valid_until',
            field=models.DateTimeField(blank=True, help_text='Consensus valid until', null=True),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='container_prefix',
            field=models.CharField(blank=True, help_text='Prefix for container names (auto-generated)', max_length=50),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='description',
            field=models.TextField(blank=True, help_text='Description and purpose of this network'),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='docker_network_name',
            field=models.CharField(blank=True, help_text='Docker network name (auto-generated)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='max_capture_size_mb',
            field=models.IntegerField(default=100, help_text='Maximum capture size per node in MB', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='name',
            field=models.CharField(help_text='Unique name for this Tor network', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='num_clients',
            field=models.PositiveIntegerField(default=2, help_text='Number of Tor Clients (SOCKS proxies)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='num_directory_authorities',
            field=models.PositiveIntegerField(default=3, help_text='Number of Directory Authorities (min. 3 for consensus)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='num_exit_relays',
            field=models.PositiveIntegerField(default=2, help_text='Number of Exit Relays', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='num_guard_relays',
            field=models.PositiveIntegerField(default=2, help_text='Number of Guard Relays', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='num_hidden_services',
            field=models.PositiveIntegerField(default=0, help_text='Number of Hidden Service nodes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='num_middle_relays',
            field=models.PositiveIntegerField(default=2, help_text='Number of Middle Relays', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name (auto-generated)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='status',
            field=models.CharField(choices=[('not_created', 'Not Created'), ('created', 'Created'), ('creating', 'Creating...'), ('bootstrapping', 'Bootstrapping...'), ('running', 'Running'), ('stopping', 'Stopping...'), ('stopped', 'Stopped'), ('error', 'Error')], default='not_created', max_length=20),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='status_message',
            field=models.TextField(blank=True, help_text='Detailed status message or error'),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='template',
            field=models.CharField(choices=[('minimal', 'Minimal (3 DA, 2 Relay, 1 Exit, 1 Client)'), ('basic', 'Basic (3 DA, 4 Relay, 2 Exit, 2 Client)'), ('standard', 'Standard (3 DA, 6 Relay, 3 Exit, 3 Client)'), ('forensic', 'Forensic (3 DA, 8 Relay, 4 Exit, 4 Client, Full Capture)'), ('custom', 'Custom Configuration')], default='basic', help_text='Network topology template', max_length=20),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='testing_tor_network',
            field=models.BooleanField(default=True, help_text='TestingTorNetwork 1 - Speeds up bootstrap'),
        ),
        migrations.AlterField(
            model_name='tornetwork',
            name='voting_interval',
            field=models.IntegerField(default=20, help_text='V3AuthVotingInterval in seconds (lower = faster bootstrap)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='bandwidth_burst',
            field=models.BigIntegerField(default=0, help_text='Burst bandwidth (bytes/s)'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='bandwidth_rate',
            field=models.BigIntegerField(default=0, help_text='Current bandwidth (bytes/s)'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='bootstrap_progress',
            field=models.IntegerField(default=0, help_text='Bootstrap progress in percent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='bytes_read',
            field=models.BigIntegerField(default=0, help_text='Bytes received'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='bytes_written',
            field=models.BigIntegerField(default=0, help_text='Bytes sent'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='capture_enabled',
            field=models.BooleanField(default=True, help_text='Traffic capture enabled for this node'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='capture_file_path',
            field=models.CharField(blank=True, help_text='Path to current capture file', max_length=255),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='capture_interface',
            field=models.CharField(default='eth0', help_text='Network interface for capture', max_length=20),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='circuits_active',
            field=models.PositiveIntegerField(default=0, help_text='Active circuits'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='circuits_created',
            field=models.PositiveIntegerField(default=0, help_text='Circuits created'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='dir_port',
            field=models.IntegerField(blank=True, help_text='Directory Port (DAs only)', null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='flags',
            field=models.JSONField(blank=True, default=list, help_text='Relay flags from consensus'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='hs_port',
            field=models.IntegerField(blank=True, help_text='Hidden Service virtual port', null=True),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='hs_target_port',
            field=models.IntegerField(blank=True, help_text='Hidden Service target port (localhost)', null=True),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='index',
            field=models.PositiveIntegerField(default=0, help_text='Index within the type (0, 1, 2, ...)'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='name',
            field=models.CharField(help_text='Node name (e.g. da1, guard1, exit2)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='node_type',
            field=models.CharField(choices=[('da', 'Directory Authority'), ('guard', 'Guard Relay'), ('middle', 'Middle Relay'), ('exit', 'Exit Relay'), ('client', 'Client (SOCKS Proxy)'), ('hs', 'Hidden Service')], help_text='Type of Tor node', max_length=10),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='onion_address',
            field=models.CharField(blank=True, help_text='.onion address (Hidden Services only)', max_length=62),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='socks_port',
            field=models.IntegerField(blank=True, help_text='SOCKS5 Proxy Port (clients only)', null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='status_message',
            field=models.TextField(blank=True, help_text='Detailed status message'),
        ),
        migrations.AlterField(
            model_name='tornode',
            name='v3_identity',
            field=models.CharField(blank=True, help_text='V3 Authority Identity (DAs only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='analysis_notes',
            field=models.TextField(blank=True, help_text='Analysis notes and findings'),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='avg_inter_packet_delay_ms',
            field=models.FloatField(blank=True, help_text='Average inter-packet delay', null=True),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='bytes_captured',
            field=models.BigIntegerField(default=0, help_text='Captured bytes'),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Capture duration in seconds'),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='file_hash_sha256',
            field=models.CharField(blank=True, help_text='SHA256 hash of file', max_length=64),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='file_path',
            field=models.CharField(help_text='Path to PCAP file', max_length=500),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='filter_expression',
            field=models.CharField(blank=True, help_text='tcpdump/BPF filter expression', max_length=500),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='first_packet_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of first packet', null=True),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='interface',
            field=models.CharField(default='eth0', help_text='Capture interface', max_length=20),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='last_packet_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last packet', null=True),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='name',
            field=models.CharField(help_text='Capture name (auto-generated)', max_length=100),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='packet_count',
            field=models.BigIntegerField(default=0, help_text='Number of packets'),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='packets_dropped',
            field=models.BigIntegerField(default=0, help_text='Dropped packets (kernel)'),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='related_circuit_id',
            field=models.CharField(blank=True, help_text='Related Circuit ID (if known)', max_length=50),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='started_at',
            field=models.DateTimeField(help_text='Capture start'),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='stopped_at',
            field=models.DateTimeField(blank=True, help_text='Capture end', null=True),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='tor_cells_detected',
            field=models.BigIntegerField(default=0, help_text='Detected Tor cells (512 bytes)'),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='unique_flows',
            field=models.IntegerField(default=0, help_text='Number of unique flows'),
        ),
    ]
