# Generated by Django 6.0.1 on 2026-01-11 17:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplexClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for this client', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Unique identifier (used for container names)', unique=True, verbose_name='Slug')),
                ('profile_name', models.CharField(blank=True, help_text='SimpleX Chat profile name (randomly generated)', max_length=50, verbose_name='Profile Name')),
                ('description', models.TextField(blank=True, help_text='Optional description for this client', verbose_name='Description')),
                ('container_id', models.CharField(blank=True, help_text='Docker container ID (set automatically)', max_length=64, verbose_name='Container ID')),
                ('container_name', models.CharField(blank=True, help_text='Docker container name (generated automatically)', max_length=100, verbose_name='Container Name')),
                ('websocket_port', models.IntegerField(help_text='Port for WebSocket connection (3031-3080)', unique=True, validators=[django.core.validators.MinValueValidator(3031), django.core.validators.MaxValueValidator(3080)], verbose_name='WebSocket Port')),
                ('data_volume', models.CharField(blank=True, help_text='Docker volume for persistent data', max_length=100, verbose_name='Data Volume')),
                ('status', models.CharField(choices=[('created', 'Created'), ('starting', 'Starting...'), ('running', 'Running'), ('stopping', 'Stopping...'), ('stopped', 'Stopped'), ('error', 'Error')], default='created', max_length=20, verbose_name='Status')),
                ('last_error', models.TextField(blank=True, help_text='Error message if status = error', verbose_name='Last Error')),
                ('use_tor', models.BooleanField(default=True, help_text='Connect via Tor (SOCKS5 proxy)', verbose_name='Use Tor')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='Sent')),
                ('messages_received', models.IntegerField(default=0, verbose_name='Received')),
                ('messages_failed', models.IntegerField(default=0, verbose_name='Failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('started_at', models.DateTimeField(blank=True, help_text='Last start time (for uptime calculation)', null=True, verbose_name='Started At')),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Active')),
                ('smp_servers', models.ManyToManyField(blank=True, help_text='SMP servers this client uses', related_name='cli_clients', to='servers.server', verbose_name='SMP Servers')),
            ],
            options={
                'verbose_name': 'SimpleX Client',
                'verbose_name_plural': 'SimpleX Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientTestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for this test run', max_length=200, verbose_name='Test Name')),
                ('message_count', models.PositiveIntegerField(default=10, help_text='Total messages to send in this test', verbose_name='Number of Messages')),
                ('interval_ms', models.PositiveIntegerField(default=1000, help_text='Delay between messages in milliseconds', verbose_name='Interval (ms)')),
                ('message_size', models.PositiveIntegerField(default=50, help_text='Size of each test message in characters', verbose_name='Message Size (chars)')),
                ('recipient_mode', models.CharField(choices=[('round_robin', 'Round Robin'), ('random', 'Random'), ('all', 'All Recipients'), ('selected', 'Selected Only')], default='round_robin', help_text='How to select recipients for each message', max_length=20, verbose_name='Recipient Mode')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('messages_sent', models.PositiveIntegerField(default=0, help_text='Number of messages sent so far', verbose_name='Messages Sent')),
                ('messages_delivered', models.PositiveIntegerField(default=0, help_text='Number of messages confirmed delivered', verbose_name='Messages Delivered')),
                ('messages_failed', models.PositiveIntegerField(default=0, help_text='Number of messages that failed to deliver', verbose_name='Messages Failed')),
                ('error_message', models.TextField(blank=True, help_text='Error details if test failed', verbose_name='Error Message')),
                ('avg_latency_ms', models.FloatField(blank=True, help_text='Average end-to-end latency in milliseconds', null=True, verbose_name='Avg Total Latency (ms)')),
                ('min_latency_ms', models.IntegerField(blank=True, help_text='Minimum end-to-end latency in milliseconds', null=True, verbose_name='Min Total Latency (ms)')),
                ('max_latency_ms', models.IntegerField(blank=True, help_text='Maximum end-to-end latency in milliseconds', null=True, verbose_name='Max Total Latency (ms)')),
                ('avg_latency_to_server_ms', models.FloatField(blank=True, help_text='Average latency from sender to SMP server', null=True, verbose_name='Avg To-Server Latency (ms)')),
                ('min_latency_to_server_ms', models.IntegerField(blank=True, help_text='Minimum latency from sender to SMP server', null=True, verbose_name='Min To-Server Latency (ms)')),
                ('max_latency_to_server_ms', models.IntegerField(blank=True, help_text='Maximum latency from sender to SMP server', null=True, verbose_name='Max To-Server Latency (ms)')),
                ('avg_latency_to_client_ms', models.FloatField(blank=True, help_text='Average latency from SMP server to recipient', null=True, verbose_name='Avg To-Client Latency (ms)')),
                ('min_latency_to_client_ms', models.IntegerField(blank=True, help_text='Minimum latency from SMP server to recipient', null=True, verbose_name='Min To-Client Latency (ms)')),
                ('max_latency_to_client_ms', models.IntegerField(blank=True, help_text='Maximum latency from SMP server to recipient', null=True, verbose_name='Max To-Client Latency (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the test execution started', null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the test finished (success, failed, or cancelled)', null=True, verbose_name='Completed At')),
                ('selected_recipients', models.ManyToManyField(blank=True, help_text='Specific recipients (only for "selected" mode)', related_name='selected_for_tests', to='clients.simplexclient', verbose_name='Selected Recipients')),
                ('sender', models.ForeignKey(help_text='Client that sends the test messages', on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='clients.simplexclient', verbose_name='Sender Client')),
            ],
            options={
                'verbose_name': 'Client Test Run',
                'verbose_name_plural': 'Client Test Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_link', models.TextField(blank=True, verbose_name='Invitation Link')),
                ('contact_name_on_a', models.CharField(blank=True, help_text='How Client A sees Client B', max_length=100, verbose_name='Name on A')),
                ('contact_name_on_b', models.CharField(blank=True, help_text='How Client B sees Client A', max_length=100, verbose_name='Name on B')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connecting', 'Connecting...'), ('connected', 'Connected'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Status')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_a', to='clients.simplexclient', verbose_name='Client A (Initiator)')),
                ('client_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_b', to='clients.simplexclient', verbose_name='Client B (Acceptor)')),
            ],
            options={
                'verbose_name': 'Client Connection',
                'verbose_name_plural': 'Client Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Content')),
                ('correlation_id', models.CharField(blank=True, max_length=50, verbose_name='Correlation ID')),
                ('tracking_id', models.CharField(blank=True, db_index=True, help_text='Unique ID for message tracking (msg_xxxxxxxxxxxx)', max_length=32, null=True, unique=True, verbose_name='Tracking ID')),
                ('delivery_status', models.CharField(choices=[('sending', '⏳ Sending'), ('sent', '✓ Server received'), ('delivered', '✓✓ Client received'), ('failed', '❌ Failed')], default='sending', max_length=20, verbose_name='Delivery Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('server_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Server Received At')),
                ('client_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Client Received At')),
                ('latency_to_server_ms', models.IntegerField(blank=True, null=True, verbose_name='Latency to Server (ms)')),
                ('latency_to_client_ms', models.IntegerField(blank=True, null=True, verbose_name='Latency to Client (ms)')),
                ('total_latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Total Latency (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.clientconnection', verbose_name='Connection')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='clients.simplexclient', verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='clients.simplexclient', verbose_name='Sender')),
                ('test_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='clients.clienttestrun', verbose_name='Test Run')),
            ],
            options={
                'verbose_name': 'Test Message',
                'verbose_name_plural': 'Test Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_type', models.CharField(choices=[('server_ack', 'Server Acknowledgment'), ('client_ack', 'Client Acknowledgment')], max_length=20, verbose_name='Receipt Type')),
                ('raw_event', models.JSONField(default=dict, help_text='Original SimpleX event JSON', verbose_name='Raw Event')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='clients.testmessage', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Delivery Receipt',
                'verbose_name_plural': 'Delivery Receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clienttestrun',
            index=models.Index(fields=['-created_at'], name='clients_cli_created_0a37e1_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttestrun',
            index=models.Index(fields=['status'], name='clients_cli_status_24a7da_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttestrun',
            index=models.Index(fields=['sender', '-created_at'], name='clients_cli_sender__49a26b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientconnection',
            unique_together={('client_a', 'client_b')},
        ),
    ]
