# Generated by Django 5.2.9 on 2025-12-26 17:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0003_server_control_port_and_more'),
        ('stresstests', '0004_alter_testresult_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplexClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Anzeigename für diesen Client', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Eindeutiger Bezeichner (wird für Container-Namen verwendet)', unique=True, verbose_name='Slug')),
                ('profile_name', models.CharField(blank=True, help_text='SimpleX Chat Profilname (falls leer wird Slug verwendet)', max_length=50, verbose_name='Profilname')),
                ('container_id', models.CharField(blank=True, help_text='Docker Container ID (wird automatisch gesetzt)', max_length=64, verbose_name='Container ID')),
                ('container_name', models.CharField(blank=True, help_text='Docker Container Name (wird automatisch generiert)', max_length=100, verbose_name='Container Name')),
                ('websocket_port', models.IntegerField(help_text='Port für WebSocket Verbindung (3031-3080)', unique=True, validators=[django.core.validators.MinValueValidator(3031), django.core.validators.MaxValueValidator(3080)], verbose_name='WebSocket Port')),
                ('data_volume', models.CharField(blank=True, help_text='Docker Volume für persistente Daten', max_length=100, verbose_name='Data Volume')),
                ('status', models.CharField(choices=[('created', 'Erstellt'), ('starting', 'Startet...'), ('running', 'Läuft'), ('stopping', 'Stoppt...'), ('stopped', 'Gestoppt'), ('error', 'Fehler')], default='created', max_length=20, verbose_name='Status')),
                ('last_error', models.TextField(blank=True, help_text='Fehlermeldung falls Status = error', verbose_name='Letzter Fehler')),
                ('use_tor', models.BooleanField(default=True, help_text='Verbindung über Tor (SOCKS5 Proxy)', verbose_name='Tor verwenden')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='Gesendet')),
                ('messages_received', models.IntegerField(default=0, verbose_name='Empfangen')),
                ('messages_failed', models.IntegerField(default=0, verbose_name='Fehlgeschlagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert')),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt aktiv')),
                ('smp_servers', models.ManyToManyField(blank=True, help_text='SMP Server die dieser Client verwendet', related_name='cli_clients', to='servers.server', verbose_name='SMP Server')),
            ],
            options={
                'verbose_name': 'SimpleX Client',
                'verbose_name_plural': 'SimpleX Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_link', models.TextField(blank=True, verbose_name='Einladungslink')),
                ('contact_name_on_a', models.CharField(blank=True, help_text='Wie Client A den Client B sieht', max_length=100, verbose_name='Name auf A')),
                ('contact_name_on_b', models.CharField(blank=True, help_text='Wie Client B den Client A sieht', max_length=100, verbose_name='Name auf B')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('connecting', 'Verbindet...'), ('connected', 'Verbunden'), ('failed', 'Fehlgeschlagen'), ('deleted', 'Gelöscht')], default='pending', max_length=20, verbose_name='Status')),
                ('last_error', models.TextField(blank=True, verbose_name='Letzter Fehler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_a', to='clients.simplexclient', verbose_name='Client A (Initiator)')),
                ('client_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_b', to='clients.simplexclient', verbose_name='Client B (Akzeptierer)')),
            ],
            options={
                'verbose_name': 'Client Verbindung',
                'verbose_name_plural': 'Client Verbindungen',
                'ordering': ['-created_at'],
                'unique_together': {('client_a', 'client_b')},
            },
        ),
        migrations.CreateModel(
            name='TestMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('correlation_id', models.CharField(blank=True, max_length=50, verbose_name='Correlation ID')),
                ('delivery_status', models.CharField(choices=[('sending', '⏳ Wird gesendet'), ('sent', '✓ Server empfangen'), ('delivered', '✓✓ Client empfangen'), ('failed', '❌ Fehlgeschlagen')], default='sending', max_length=20, verbose_name='Zustellstatus')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet um')),
                ('server_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Server empfangen um')),
                ('client_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Client empfangen um')),
                ('latency_to_server_ms', models.IntegerField(blank=True, null=True, verbose_name='Latenz zum Server (ms)')),
                ('latency_to_client_ms', models.IntegerField(blank=True, null=True, verbose_name='Latenz zum Client (ms)')),
                ('total_latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Gesamtlatenz (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.clientconnection', verbose_name='Verbindung')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='clients.simplexclient', verbose_name='Empfänger')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='clients.simplexclient', verbose_name='Sender')),
                ('test_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cli_messages', to='stresstests.testrun', verbose_name='Test Run')),
            ],
            options={
                'verbose_name': 'Test Nachricht',
                'verbose_name_plural': 'Test Nachrichten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_type', models.CharField(choices=[('server_ack', 'Server Acknowledgment'), ('client_ack', 'Client Acknowledgment')], max_length=20, verbose_name='Receipt Typ')),
                ('raw_event', models.JSONField(default=dict, help_text='Original SimpleX Event JSON', verbose_name='Raw Event')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='clients.testmessage', verbose_name='Nachricht')),
            ],
            options={
                'verbose_name': 'Delivery Receipt',
                'verbose_name_plural': 'Delivery Receipts',
                'ordering': ['-received_at'],
            },
        ),
    ]
