# Generated by Django 6.0.1 on 2026-01-11 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chutney', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplexclient',
            name='use_tor',
        ),
        migrations.AddField(
            model_name='simplexclient',
            name='chutnex_network',
            field=models.ForeignKey(blank=True, help_text='Private Tor network (required for ChutneX modes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simplex_clients', to='chutney.tornetwork', verbose_name='ChutneX Network'),
        ),
        migrations.AddField(
            model_name='simplexclient',
            name='chutnex_socks_port',
            field=models.IntegerField(blank=True, help_text='SOCKS port from ChutneX client node (9000-9099)', null=True, validators=[django.core.validators.MinValueValidator(9000), django.core.validators.MaxValueValidator(9099)], verbose_name='ChutneX SOCKS Port'),
        ),
        migrations.AddField(
            model_name='simplexclient',
            name='connection_mode',
            field=models.CharField(choices=[('direct', 'Direct (no Tor)'), ('public_tor', 'Public Tor (:9050)'), ('chutnex_internal', 'ChutneX Internal (same network)'), ('chutnex_external', 'ChutneX External (via SOCKS)')], default='public_tor', help_text='How the client connects to servers', max_length=20, verbose_name='Connection Mode'),
        ),
    ]
