# Generated by Django 5.2.9 on 2025-12-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplexclient',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Beschreibung für diesen Client', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='profile_name',
            field=models.CharField(blank=True, help_text='SimpleX Chat Profilname (zufällig generiert)', max_length=50, verbose_name='Profilname'),
        ),
    ]
