# Generated by Django 5.2.9 on 2025-12-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_simplexclient_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplexclient',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt des letzten Starts (für Uptime-Berechnung)', null=True, verbose_name='Gestartet um'),
        ),
    ]
