# Generated by Django 6.0 on 2026-01-02 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_simplexclient_started_at'),
        ('servers', '0003_server_control_port_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientconnection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Connection', 'verbose_name_plural': 'Client Connections'},
        ),
        migrations.AlterModelOptions(
            name='testmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Test Message', 'verbose_name_plural': 'Test Messages'},
        ),
        migrations.AddField(
            model_name='testmessage',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID for message tracking (msg_xxxxxxxxxxxx)', max_length=32, null=True, unique=True, verbose_name='Tracking ID'),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='client_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_b', to='clients.simplexclient', verbose_name='Client B (Acceptor)'),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='contact_name_on_a',
            field=models.CharField(blank=True, help_text='How Client A sees Client B', max_length=100, verbose_name='Name on A'),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='contact_name_on_b',
            field=models.CharField(blank=True, help_text='How Client B sees Client A', max_length=100, verbose_name='Name on B'),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='invitation_link',
            field=models.TextField(blank=True, verbose_name='Invitation Link'),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Last Error'),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connecting', 'Connecting...'), ('connected', 'Connected'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='clients.testmessage', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='raw_event',
            field=models.JSONField(default=dict, help_text='Original SimpleX event JSON', verbose_name='Raw Event'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='receipt_type',
            field=models.CharField(choices=[('server_ack', 'Server Acknowledgment'), ('client_ack', 'Client Acknowledgment')], max_length=20, verbose_name='Receipt Type'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='container_id',
            field=models.CharField(blank=True, help_text='Docker container ID (set automatically)', max_length=64, verbose_name='Container ID'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='container_name',
            field=models.CharField(blank=True, help_text='Docker container name (generated automatically)', max_length=100, verbose_name='Container Name'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='data_volume',
            field=models.CharField(blank=True, help_text='Docker volume for persistent data', max_length=100, verbose_name='Data Volume'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this client', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Active'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='last_error',
            field=models.TextField(blank=True, help_text='Error message if status = error', verbose_name='Last Error'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='messages_failed',
            field=models.IntegerField(default=0, verbose_name='Failed'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='messages_received',
            field=models.IntegerField(default=0, verbose_name='Received'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='messages_sent',
            field=models.IntegerField(default=0, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='name',
            field=models.CharField(help_text='Display name for this client', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='profile_name',
            field=models.CharField(blank=True, help_text='SimpleX Chat profile name (randomly generated)', max_length=50, verbose_name='Profile Name'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='slug',
            field=models.SlugField(help_text='Unique identifier (used for container names)', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='smp_servers',
            field=models.ManyToManyField(blank=True, help_text='SMP servers this client uses', related_name='cli_clients', to='servers.server', verbose_name='SMP Servers'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Last start time (for uptime calculation)', null=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('starting', 'Starting...'), ('running', 'Running'), ('stopping', 'Stopping...'), ('stopped', 'Stopped'), ('error', 'Error')], default='created', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='use_tor',
            field=models.BooleanField(default=True, help_text='Connect via Tor (SOCKS5 proxy)', verbose_name='Use Tor'),
        ),
        migrations.AlterField(
            model_name='simplexclient',
            name='websocket_port',
            field=models.IntegerField(help_text='Port for WebSocket connection (3031-3080)', unique=True, validators=[django.core.validators.MinValueValidator(3031), django.core.validators.MaxValueValidator(3080)], verbose_name='WebSocket Port'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='client_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Client Received At'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.clientconnection', verbose_name='Connection'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='delivery_status',
            field=models.CharField(choices=[('sending', '⏳ Sending'), ('sent', '✓ Server received'), ('delivered', '✓✓ Client received'), ('failed', '❌ Failed')], default='sending', max_length=20, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='latency_to_client_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Latency to Client (ms)'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='latency_to_server_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Latency to Server (ms)'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='clients.simplexclient', verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='server_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Server Received At'),
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='total_latency_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Latency (ms)'),
        ),
    ]
