# Generated by Django 6.0 on 2026-01-02 15:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientconnection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this test run', max_length=100, verbose_name='Test Name')),
                ('message_count', models.IntegerField(default=10, help_text='Number of messages to send', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Message Count')),
                ('interval_ms', models.IntegerField(default=1000, help_text='Pause between messages in milliseconds', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(60000)], verbose_name='Interval (ms)')),
                ('message_size', models.IntegerField(default=50, help_text='Approximate message length in characters', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(5000)], verbose_name='Message Size')),
                ('recipient_mode', models.CharField(choices=[('all', 'All contacts'), ('random', 'Random'), ('round_robin', 'Round-Robin'), ('selected', 'Selected contacts')], default='round_robin', max_length=20, verbose_name='Recipient Mode')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='Messages Sent')),
                ('messages_delivered', models.IntegerField(default=0, verbose_name='Messages Delivered')),
                ('messages_failed', models.IntegerField(default=0, verbose_name='Messages Failed')),
                ('avg_latency_ms', models.FloatField(blank=True, null=True, verbose_name='Avg Latency (ms)')),
                ('min_latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Min Latency (ms)')),
                ('max_latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Max Latency (ms)')),
                ('success_rate', models.FloatField(blank=True, null=True, verbose_name='Success Rate (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('selected_recipients', models.ManyToManyField(blank=True, related_name='test_runs_as_recipient', to='clients.simplexclient', verbose_name='Selected Recipients')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='clients.simplexclient', verbose_name='Sender Client')),
            ],
            options={
                'verbose_name': 'Test Run',
                'verbose_name_plural': 'Test Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
