# Generated by Django 6.0 on 2026-01-03 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_testrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Test Name')),
                ('message_count', models.PositiveIntegerField(default=10, verbose_name='Number of Messages')),
                ('interval_ms', models.PositiveIntegerField(default=1000, verbose_name='Interval (ms)')),
                ('message_size', models.PositiveIntegerField(default=50, verbose_name='Message Size (chars)')),
                ('recipient_mode', models.CharField(choices=[('round_robin', 'Round Robin'), ('random', 'Random'), ('all', 'All Recipients'), ('selected', 'Selected Only')], default='round_robin', max_length=20, verbose_name='Recipient Mode')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_delivered', models.PositiveIntegerField(default=0)),
                ('messages_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('selected_recipients', models.ManyToManyField(blank=True, related_name='selected_for_tests', to='clients.simplexclient', verbose_name='Selected Recipients')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='clients.simplexclient', verbose_name='Sender Client')),
            ],
            options={
                'verbose_name': 'Client Test Run',
                'verbose_name_plural': 'Client Test Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='testmessage',
            name='test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='clients.clienttestrun', verbose_name='Test Run'),
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
    ]
