# Generated by Django 6.0 on 2026-01-03 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clienttestrun_alter_testmessage_test_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttestrun',
            name='avg_latency_ms',
            field=models.FloatField(blank=True, help_text='Average end-to-end latency in milliseconds', null=True, verbose_name='Avg Total Latency (ms)'),
        ),
        migrations.AddField(
            model_name='clienttestrun',
            name='avg_latency_to_client_ms',
            field=models.FloatField(blank=True, help_text='Average latency from SMP server to recipient', null=True, verbose_name='Avg To-Client Latency (ms)'),
        ),
        migrations.AddField(
            model_name='clienttestrun',
            name='avg_latency_to_server_ms',
            field=models.FloatField(blank=True, help_text='Average latency from sender to SMP server', null=True, verbose_name='Avg To-Server Latency (ms)'),
        ),
        migrations.AddField(
            model_name='clienttestrun',
            name='max_latency_ms',
            field=models.IntegerField(blank=True, help_text='Maximum end-to-end latency in milliseconds', null=True, verbose_name='Max Total Latency (ms)'),
        ),
        migrations.AddField(
            model_name='clienttestrun',
            name='max_latency_to_client_ms',
            field=models.IntegerField(blank=True, help_text='Maximum latency from SMP server to recipient', null=True, verbose_name='Max To-Client Latency (ms)'),
        ),
        migrations.AddField(
            model_name='clienttestrun',
            name='max_latency_to_server_ms',
            field=models.IntegerField(blank=True, help_text='Maximum latency from sender to SMP server', null=True, verbose_name='Max To-Server Latency (ms)'),
        ),
        migrations.AddField(
            model_name='clienttestrun',
            name='min_latency_ms',
            field=models.IntegerField(blank=True, help_text='Minimum end-to-end latency in milliseconds', null=True, verbose_name='Min Total Latency (ms)'),
        ),
        migrations.AddField(
            model_name='clienttestrun',
            name='min_latency_to_client_ms',
            field=models.IntegerField(blank=True, help_text='Minimum latency from SMP server to recipient', null=True, verbose_name='Min To-Client Latency (ms)'),
        ),
        migrations.AddField(
            model_name='clienttestrun',
            name='min_latency_to_server_ms',
            field=models.IntegerField(blank=True, help_text='Minimum latency from sender to SMP server', null=True, verbose_name='Min To-Server Latency (ms)'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the test finished (success, failed, or cancelled)', null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if test failed', verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='interval_ms',
            field=models.PositiveIntegerField(default=1000, help_text='Delay between messages in milliseconds', verbose_name='Interval (ms)'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='message_count',
            field=models.PositiveIntegerField(default=10, help_text='Total messages to send in this test', verbose_name='Number of Messages'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='message_size',
            field=models.PositiveIntegerField(default=50, help_text='Size of each test message in characters', verbose_name='Message Size (chars)'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='messages_delivered',
            field=models.PositiveIntegerField(default=0, help_text='Number of messages confirmed delivered', verbose_name='Messages Delivered'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='messages_failed',
            field=models.PositiveIntegerField(default=0, help_text='Number of messages that failed to deliver', verbose_name='Messages Failed'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='messages_sent',
            field=models.PositiveIntegerField(default=0, help_text='Number of messages sent so far', verbose_name='Messages Sent'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='name',
            field=models.CharField(help_text='Display name for this test run', max_length=200, verbose_name='Test Name'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='recipient_mode',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('random', 'Random'), ('all', 'All Recipients'), ('selected', 'Selected Only')], default='round_robin', help_text='How to select recipients for each message', max_length=20, verbose_name='Recipient Mode'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='selected_recipients',
            field=models.ManyToManyField(blank=True, help_text='Specific recipients (only for "selected" mode)', related_name='selected_for_tests', to='clients.simplexclient', verbose_name='Selected Recipients'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='sender',
            field=models.ForeignKey(help_text='Client that sends the test messages', on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='clients.simplexclient', verbose_name='Sender Client'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the test execution started', null=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='clienttestrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='clienttestrun',
            index=models.Index(fields=['-created_at'], name='clients_cli_created_0a37e1_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttestrun',
            index=models.Index(fields=['status'], name='clients_cli_status_24a7da_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttestrun',
            index=models.Index(fields=['sender', '-created_at'], name='clients_cli_sender__49a26b_idx'),
        ),
    ]
