# Generated by Django 6.0 on 2025-12-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20)),
                ('num_clients', models.PositiveIntegerField(default=2)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('message_interval_seconds', models.PositiveIntegerField(default=5)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_received', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(blank=True, null=True)),
                ('min_latency_ms', models.FloatField(blank=True, null=True)),
                ('max_latency_ms', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('servers', models.ManyToManyField(blank=True, related_name='test_runs', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='stresstests.testrun')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
