# Generated by Django 5.2.9 on 2025-12-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stresstests', '0002_new_test_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrunold',
            name='servers',
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stresstests.test',),
        ),
        migrations.RenameIndex(
            model_name='testresult',
            new_name='stresstests_test_id_678da2_idx',
            old_name='stresstests_test_id_7a1234_idx',
        ),
        migrations.RenameIndex(
            model_name='testresult',
            new_name='stresstests_server__c625ad_idx',
            old_name='stresstests_server__abc123_idx',
        ),
        migrations.DeleteModel(
            name='TestRunOld',
        ),
    ]
