# Generated by Django 5.2.9 on 2025-12-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stresstests', '0003_remove_testrunold_servers_testrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='error_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
