# Generated by Django 6.0.1 on 2026-01-11 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#0ea5e9', max_length=7)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('server_type', models.CharField(choices=[('smp', 'SMP'), ('xftp', 'XFTP'), ('ntf', 'NTF')], default='smp', max_length=10)),
                ('address', models.TextField(blank=True, help_text='Full smp://... or xftp://... URL (auto-generated for Docker servers)')),
                ('description', models.TextField(blank=True, help_text='Notes about this server')),
                ('location', models.CharField(blank=True, help_text='Physical location', max_length=100)),
                ('is_docker_hosted', models.BooleanField(default=False, help_text='Run this server locally in a Docker container', verbose_name='Docker Hosted')),
                ('hosting_mode', models.CharField(choices=[('ip', 'IP Address (LAN)'), ('tor', 'Tor Hidden Service (.onion)')], default='ip', help_text='How the server should be accessible', max_length=10, verbose_name='Hosting Mode')),
                ('host_ip', models.CharField(blank=True, default='0.0.0.0', help_text='IP address for server certificate (use host IP for LAN access)', max_length=45, verbose_name='Host IP')),
                ('onion_address', models.CharField(blank=True, help_text='Tor hidden service address (auto-generated)', max_length=62, verbose_name='Onion Address')),
                ('container_id', models.CharField(blank=True, help_text='Docker container ID (set automatically)', max_length=64, verbose_name='Container ID')),
                ('container_name', models.CharField(blank=True, help_text='Docker container name (generated automatically)', max_length=100, verbose_name='Container Name')),
                ('data_volume', models.CharField(blank=True, help_text='Docker volume for persistent data', max_length=100, verbose_name='Data Volume')),
                ('config_volume', models.CharField(blank=True, help_text='Docker volume for configuration', max_length=100, verbose_name='Config Volume')),
                ('exposed_port', models.IntegerField(blank=True, help_text='Host port for Docker container (5223 for SMP, 443 for XFTP/NTF)', null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='Exposed Port')),
                ('docker_status', models.CharField(choices=[('not_created', 'Not Created'), ('created', 'Created'), ('starting', 'Starting...'), ('running', 'Running'), ('stopping', 'Stopping...'), ('stopped', 'Stopped'), ('error', 'Error')], default='not_created', max_length=20, verbose_name='Docker Status')),
                ('docker_error', models.TextField(blank=True, help_text='Last Docker error message', verbose_name='Docker Error')),
                ('generated_fingerprint', models.CharField(blank=True, help_text='Server fingerprint (extracted after container initialization)', max_length=100, verbose_name='Generated Fingerprint')),
                ('generated_address', models.TextField(blank=True, help_text='Full server address (generated after container initialization)', verbose_name='Generated Address')),
                ('is_active', models.BooleanField(default=True, help_text='Include in tests')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Temporarily exclude from tests')),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='unknown', max_length=20)),
                ('last_latency', models.IntegerField(blank=True, help_text='Last latency in ms', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message')),
                ('custom_timeout', models.IntegerField(blank=True, help_text='Custom timeout in seconds', null=True)),
                ('priority', models.IntegerField(default=5, help_text='Priority 1-10 for load balancing')),
                ('expected_uptime', models.IntegerField(default=99, help_text='Expected uptime percentage')),
                ('max_latency', models.IntegerField(default=5000, help_text='Max acceptable latency in ms')),
                ('total_checks', models.IntegerField(default=0)),
                ('successful_checks', models.IntegerField(default=0)),
                ('avg_latency', models.IntegerField(blank=True, help_text='Average latency in ms', null=True)),
                ('ssh_host', models.CharField(blank=True, help_text='SSH host', max_length=255)),
                ('ssh_port', models.IntegerField(default=22, help_text='SSH port')),
                ('ssh_user', models.CharField(blank=True, help_text='SSH username', max_length=100)),
                ('ssh_key_path', models.CharField(blank=True, help_text='Path to SSH key', max_length=500)),
                ('control_port_enabled', models.BooleanField(default=False, help_text='Control port available')),
                ('control_port', models.IntegerField(default=5224, help_text='Control port number')),
                ('control_port_admin_password', models.CharField(blank=True, help_text='Admin password', max_length=100)),
                ('control_port_user_password', models.CharField(blank=True, help_text='User password', max_length=100)),
                ('simplex_version', models.CharField(blank=True, max_length=50)),
                ('simplex_fingerprint', models.CharField(blank=True, max_length=100)),
                ('store_log_enabled', models.BooleanField(default=True)),
                ('restore_messages', models.BooleanField(default=True)),
                ('expire_messages_days', models.IntegerField(default=21)),
                ('log_stats_enabled', models.BooleanField(default=True)),
                ('new_queues_allowed', models.BooleanField(default=True)),
                ('websockets_enabled', models.BooleanField(default=False)),
                ('telegraf_enabled', models.BooleanField(default=False, help_text='Enable Telegraf metrics collection')),
                ('telegraf_interval', models.IntegerField(default=10, help_text='Collection interval in seconds')),
                ('influxdb_url', models.CharField(blank=True, default='http://localhost:8086', max_length=255)),
                ('influxdb_token', models.CharField(blank=True, help_text='InfluxDB API token', max_length=255)),
                ('influxdb_org', models.CharField(blank=True, default='simplex', max_length=100)),
                ('influxdb_bucket', models.CharField(blank=True, default='simplex-metrics', max_length=100)),
                ('simplex_config_path', models.CharField(default='/etc/opt/simplex', help_text='Config directory', max_length=255)),
                ('simplex_data_path', models.CharField(default='/var/opt/simplex', help_text='Data directory', max_length=255)),
                ('simplex_stats_file', models.CharField(default='/var/opt/simplex/smp-server-stats.daily.log', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='servers', to='servers.category')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
