# Generated by Django 6.0 on 2025-12-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('server_type', models.CharField(choices=[('smp', 'SMP'), ('xftp', 'XFTP')], default='smp', max_length=10)),
                ('address', models.TextField(help_text='Vollständige smp://... oder xftp://... URL')),
                ('is_active', models.BooleanField(default=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('unknown', 'Unbekannt'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Fehler')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
