# Generated by Django 6.0.1 on 2026-01-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chutney', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='chutnex_network',
            field=models.ForeignKey(blank=True, help_text='Private Tor network for this server (required for ChutneX mode)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_servers', to='chutney.tornetwork', verbose_name='ChutneX Network'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hosting_mode',
            field=models.CharField(choices=[('ip', 'IP Address (LAN)'), ('tor', 'Tor Hidden Service (Public)'), ('chutnex', 'ChutneX Private Network')], default='ip', help_text='How the server should be accessible', max_length=10, verbose_name='Hosting Mode'),
        ),
    ]
