# Generated by Django 5.2.9 on 2025-12-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='server',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='address',
            field=models.TextField(help_text='Full smp://... or xftp://... URL'),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='unknown', max_length=20),
        ),
    ]
