# Generated by Django 5.2.9 on 2025-12-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='avg_latency',
            field=models.IntegerField(blank=True, help_text='Average latency in ms', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='custom_timeout',
            field=models.IntegerField(blank=True, help_text='Custom timeout in seconds (default: 30s clearnet, 120s onion)', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, help_text='Notes about this server'),
        ),
        migrations.AddField(
            model_name='server',
            name='expected_uptime',
            field=models.IntegerField(default=99, help_text='Expected uptime percentage'),
        ),
        migrations.AddField(
            model_name='server',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message'),
        ),
        migrations.AddField(
            model_name='server',
            name='last_latency',
            field=models.IntegerField(blank=True, help_text='Last measured latency in ms', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location or identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Temporarily exclude from tests'),
        ),
        migrations.AddField(
            model_name='server',
            name='max_latency',
            field=models.IntegerField(default=5000, help_text='Maximum acceptable latency in ms'),
        ),
        migrations.AddField(
            model_name='server',
            name='priority',
            field=models.IntegerField(default=5, help_text='Priority 1-10 for load balancing'),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_host',
            field=models.CharField(blank=True, help_text='SSH host (if different from server)', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_key_path',
            field=models.CharField(blank=True, help_text='Path to SSH private key', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_port',
            field=models.IntegerField(default=22, help_text='SSH port'),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_user',
            field=models.CharField(blank=True, help_text='SSH username', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='successful_checks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='total_checks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Include in tests'),
        ),
    ]
