# Generated by Django 5.2.9 on 2025-12-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_avg_latency_server_custom_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='control_port',
            field=models.IntegerField(default=5224, help_text='Control port number'),
        ),
        migrations.AddField(
            model_name='server',
            name='control_port_admin_password',
            field=models.CharField(blank=True, help_text='Admin password', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='control_port_enabled',
            field=models.BooleanField(default=False, help_text='Control port available'),
        ),
        migrations.AddField(
            model_name='server',
            name='control_port_user_password',
            field=models.CharField(blank=True, help_text='User password', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='expire_messages_days',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='server',
            name='influxdb_bucket',
            field=models.CharField(blank=True, default='simplex-metrics', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='influxdb_org',
            field=models.CharField(blank=True, default='simplex', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='influxdb_token',
            field=models.CharField(blank=True, help_text='InfluxDB API token', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='influxdb_url',
            field=models.CharField(blank=True, default='http://localhost:8086', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='log_stats_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='new_queues_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='restore_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='simplex_config_path',
            field=models.CharField(default='/etc/opt/simplex', help_text='Config directory', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='simplex_data_path',
            field=models.CharField(default='/var/opt/simplex', help_text='Data directory', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='simplex_fingerprint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='simplex_stats_file',
            field=models.CharField(default='/var/opt/simplex/smp-server-stats.daily.log', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='simplex_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='store_log_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='telegraf_enabled',
            field=models.BooleanField(default=False, help_text='Enable Telegraf metrics collection'),
        ),
        migrations.AddField(
            model_name='server',
            name='telegraf_interval',
            field=models.IntegerField(default=10, help_text='Collection interval in seconds'),
        ),
        migrations.AddField(
            model_name='server',
            name='websockets_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='custom_timeout',
            field=models.IntegerField(blank=True, help_text='Custom timeout in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_latency',
            field=models.IntegerField(blank=True, help_text='Last latency in ms', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location', max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='max_latency',
            field=models.IntegerField(default=5000, help_text='Max acceptable latency in ms'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_host',
            field=models.CharField(blank=True, help_text='SSH host', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_key_path',
            field=models.CharField(blank=True, help_text='Path to SSH key', max_length=500),
        ),
    ]
