# Generated by Django 6.0 on 2026-01-08 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_control_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='config_volume',
            field=models.CharField(blank=True, help_text='Docker volume for configuration', max_length=100, verbose_name='Config Volume'),
        ),
        migrations.AddField(
            model_name='server',
            name='container_id',
            field=models.CharField(blank=True, help_text='Docker container ID (set automatically)', max_length=64, verbose_name='Container ID'),
        ),
        migrations.AddField(
            model_name='server',
            name='container_name',
            field=models.CharField(blank=True, help_text='Docker container name (generated automatically)', max_length=100, verbose_name='Container Name'),
        ),
        migrations.AddField(
            model_name='server',
            name='data_volume',
            field=models.CharField(blank=True, help_text='Docker volume for persistent data', max_length=100, verbose_name='Data Volume'),
        ),
        migrations.AddField(
            model_name='server',
            name='docker_error',
            field=models.TextField(blank=True, help_text='Last Docker error message', verbose_name='Docker Error'),
        ),
        migrations.AddField(
            model_name='server',
            name='docker_status',
            field=models.CharField(choices=[('not_created', 'Not Created'), ('created', 'Created'), ('starting', 'Starting...'), ('running', 'Running'), ('stopping', 'Stopping...'), ('stopped', 'Stopped'), ('error', 'Error')], default='not_created', max_length=20, verbose_name='Docker Status'),
        ),
        migrations.AddField(
            model_name='server',
            name='exposed_port',
            field=models.IntegerField(blank=True, help_text='Host port for Docker container (5223 for SMP, 443 for XFTP/NTF)', null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='Exposed Port'),
        ),
        migrations.AddField(
            model_name='server',
            name='generated_address',
            field=models.TextField(blank=True, help_text='Full server address (generated after container initialization)', verbose_name='Generated Address'),
        ),
        migrations.AddField(
            model_name='server',
            name='generated_fingerprint',
            field=models.CharField(blank=True, help_text='Server fingerprint (extracted after container initialization)', max_length=100, verbose_name='Generated Fingerprint'),
        ),
        migrations.AddField(
            model_name='server',
            name='is_docker_hosted',
            field=models.BooleanField(default=False, help_text='Run this server locally in a Docker container', verbose_name='Docker Hosted'),
        ),
        migrations.AlterField(
            model_name='server',
            name='address',
            field=models.TextField(blank=True, help_text='Full smp://... or xftp://... URL (auto-generated for Docker servers)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('smp', 'SMP'), ('xftp', 'XFTP'), ('ntf', 'NTF')], default='smp', max_length=10),
        ),
    ]
