# Generated by Django 6.0 on 2026-01-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_server_config_volume_server_container_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='host_ip',
            field=models.CharField(blank=True, default='0.0.0.0', help_text='IP address for server certificate (use host IP for LAN access)', max_length=45, verbose_name='Host IP'),
        ),
        migrations.AddField(
            model_name='server',
            name='hosting_mode',
            field=models.CharField(choices=[('ip', 'IP Address (LAN)'), ('tor', 'Tor Hidden Service (.onion)')], default='ip', help_text='How the server should be accessible', max_length=10, verbose_name='Hosting Mode'),
        ),
        migrations.AddField(
            model_name='server',
            name='onion_address',
            field=models.CharField(blank=True, help_text='Tor hidden service address (auto-generated)', max_length=62, verbose_name='Onion Address'),
        ),
    ]
